# config.py
import os
import secrets
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    SECRET_KEY = secrets.token_hex(32)
GROK_API_KEY = os.getenv("GROK_API_KEY", "")
GROK_MODEL = os.getenv("GROK_MODEL", "grok-2-1212")
DB_PATH = "/tmp/mcq.db" if os.environ.get("VERCEL") else "database/mcq.db"
UPLOAD_FOLDER = "/tmp/uploads" if os.environ.get("VERCEL") else "uploads"
ALLOWED_EXT = {"pdf", "docx", "txt", "pptx"}

# ---------------------------------------------------------------------------
# Agentic AI + RAG configuration (Phase 1+). All additive; defaults preserve
# the existing behaviour so nothing changes until a feature flag is flipped.
# ---------------------------------------------------------------------------
IS_VERCEL = bool(os.environ.get("VERCEL"))

# --- LLM provider abstraction --------------------------------------------
# One of: "auto" | "groq" | "xai" | "openai" | "gemini" | "anthropic".
# "auto" keeps the legacy behaviour: detect Groq vs xAI from the key prefix.
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "auto").strip().lower()

# Unified key/model. LLM_API_KEY falls back to the historical GROK_API_KEY so
# existing .env files keep working untouched.
LLM_API_KEY = os.getenv("LLM_API_KEY", GROK_API_KEY)
LLM_MODEL = os.getenv("LLM_MODEL", GROK_MODEL)

# Per-provider key overrides (optional; only used when explicitly selected).
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")

LLM_TIMEOUT = int(os.getenv("LLM_TIMEOUT", "45"))
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0.3"))

# Output token budget for MCQ generation. Providers apply a modest default cap
# (often ~1-4k) which truncates the JSON array mid-object on larger requests --
# that's what silently turned "25 questions" into a handful. We request a budget
# scaled to the batch size, floored so small batches still get room to breathe.
# ~330 tokens covers one question with 4 options plus bloom/source_hint metadata.
LLM_TOKENS_PER_QUESTION = int(os.getenv("LLM_TOKENS_PER_QUESTION", "330"))
LLM_MAX_OUTPUT_TOKENS = int(os.getenv("LLM_MAX_OUTPUT_TOKENS", "16000"))


def mcq_token_budget(num_questions: int) -> int:
    """Output token ceiling for a batch of `num_questions` MCQs."""
    return min(LLM_MAX_OUTPUT_TOKENS, max(1500, num_questions * LLM_TOKENS_PER_QUESTION + 400))

# Wall-clock budget for the whole RAG MCQ pipeline. Must stay under the serverless
# function limit (vercel.json maxDuration=60) so generation is never killed
# mid-flight; the pipeline stops retrying once this budget (minus one LLM_TIMEOUT
# of headroom) is exhausted and returns whatever it has collected.
PIPELINE_DEADLINE_SECONDS = int(os.getenv("PIPELINE_DEADLINE_SECONDS", "55"))

# --- Upload/generation throttle (app-level, protects the LLM from bursts) --
# Minimum seconds between two MCQ-generation requests, and the max generations
# allowed per 5-minute window. Set the cooldown to 0 to disable it entirely.
# Deliberately lenient by default — a single user iterating on their own
# material shouldn't be blocked; this only guards against runaway loops.
GENERATION_COOLDOWN_SECONDS = int(os.getenv("GENERATION_COOLDOWN_SECONDS", "3"))
GENERATION_MAX_PER_5MIN = int(os.getenv("GENERATION_MAX_PER_5MIN", "10"))

# --- AI pipeline selection ------------------------------------------------
# "legacy"  -> single-shot generate_mcqs (current behaviour, the safe default)
# "rag"     -> retrieval-augmented agent pipeline (enabled in Phase 4)
AI_PIPELINE = os.getenv("AI_PIPELINE", "legacy").strip().lower()

# --- Generation & verification quality (RAG pipeline only) ----------------
# Generation runs at a low temperature so questions stay faithful to the
# retrieved context instead of drifting into the model's own memory. Kept
# separate from LLM_TEMPERATURE (which the legacy path and other agents use).
LLM_GENERATION_TEMPERATURE = float(os.getenv("LLM_GENERATION_TEMPERATURE", "0.1"))

# Context Validation: before generating, confirm the retrieved context actually
# supports grounded questions. When it confidently reports the context is
# insufficient, the pipeline falls back to the fuller-text legacy path rather
# than let the generator invent facts. Fail-open: any error => treated as
# sufficient so generation is never blocked by a flaky check.
CONTEXT_VALIDATION_ENABLED = os.getenv("CONTEXT_VALIDATION_ENABLED", "true").strip().lower() in ("1", "true", "yes", "on")

# Fact Verification: after generation, an independent agent checks each MCQ
# against the context (answer supported, distractors wrong, one correct answer,
# unambiguous, explanation matches). Rejected questions are regenerated by the
# existing top-up loop. Fail-open: any error => questions pass through unchanged.
FACT_VERIFICATION_ENABLED = os.getenv("FACT_VERIFICATION_ENABLED", "true").strip().lower() in ("1", "true", "yes", "on")

# Minimum model self-reported confidence [0,1] for a verified MCQ to be kept.
FACT_VERIFICATION_MIN_CONFIDENCE = float(os.getenv("FACT_VERIFICATION_MIN_CONFIDENCE", "0.6"))

# --- LLM rate-limit retry --------------------------------------------------
# Providers (especially free tiers) return HTTP 429 on brief bursts. A single
# generation fires several calls in quick succession (top-up loop + context
# validation + fact verification), so a lone 429 shouldn't abort the whole
# request. On 429 the LLM layer retries with exponential backoff, honoring the
# provider's Retry-After header when present.
LLM_MAX_RETRIES = int(os.getenv("LLM_MAX_RETRIES", "3"))
LLM_RETRY_BACKOFF = float(os.getenv("LLM_RETRY_BACKOFF", "1.5"))  # base seconds, doubled each retry
LLM_RETRY_MAX_WAIT = float(os.getenv("LLM_RETRY_MAX_WAIT", "8"))  # cap per individual wait

# Answer Evaluation: below this confidence the grader is asked to re-evaluate
# once (per the brief's failure-handling rule).
ANSWER_EVAL_REEVAL_CONFIDENCE = float(os.getenv("ANSWER_EVAL_REEVAL_CONFIDENCE", "0.7"))

# --- Embeddings -----------------------------------------------------------
# "auto"                -> SentenceTransformer if importable, else hashing
# "sentence_transformer"-> force local ST model (never available on Vercel)
# "remote"              -> OpenAI/Gemini embedding endpoint
# "hashing"             -> pure-Python fallback, zero heavy deps
EMBEDDING_BACKEND = os.getenv("EMBEDDING_BACKEND", "auto").strip().lower()
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")
EMBEDDING_DIM = int(os.getenv("EMBEDDING_DIM", "384"))  # MiniLM native dim
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "64"))

# --- Vector store ---------------------------------------------------------
# "chroma" (default) -> ChromaDB persistent client
# "sqlite"           -> vectors as BLOBs in mcq.db + numpy cosine (Vercel-safe)
# "faiss"            -> FAISS index (opt-in; needs a compatible wheel)
# On Vercel the read-only FS forces the sqlite store regardless of this value.
VECTOR_STORE = os.getenv("VECTOR_STORE", "sqlite" if IS_VERCEL else "chroma").strip().lower()
CHROMA_PATH = os.getenv("CHROMA_PATH", "/tmp/chroma_db" if IS_VERCEL else "chroma_db")

# --- Chunking -------------------------------------------------------------
CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "1000"))       # chars per chunk
CHUNK_OVERLAP = int(os.getenv("CHUNK_OVERLAP", "150"))  # char overlap
RETRIEVAL_TOP_K = int(os.getenv("RETRIEVAL_TOP_K", "12"))
CONTEXT_MAX_CHARS = int(os.getenv("CONTEXT_MAX_CHARS", "12000"))
